version: '3.8'

services:
  client:
    build: ./frontend
    ports: 
      - "5173:80"

  server:
    build: ./backend
    environment:
      DB_URL: jdbc:postgresql://db:5435/mydb
      DB_USER: postgres
      DB_PASS: 12345
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



